@startuml
scale 1.5

title <DesktopChara>

object DesktopChara{
    WinMain()
}

object Config {
    setup()
}

package Screen {
    enum MouseCondition {
        None
        Click_L
        Click_R
    }

    class Screen {
        -bool StartFlag_L
        -POINT StartCursorPos
        -POINT NowCursorPos
        -POINT StartWindowPos
        -MouseCondition mc
        -void MoveWindow()
        -void MouseClick()
        -void ContextMenu()
        +void Update()
    }
    MouseCondition .ri- Screen
    POINT .le- Screen
}

package Character {
    enum Actions {
        None
        Blink
        Surprised
        Callout
    }

    class Character {
        -Actions ActType
        -int graphHandle[12] callout
        -int Counter
        -int sdNum
        -bool AnimeFlag isCallout

        -GetAction()
        +void Update()
        +void Draw()
    }

    Actions .le- Character
}

Character -> DesktopChara :chara
Screen -> DesktopChara :sc
Config -ri> DesktopChara

@endtuml
